# Generated by Django 4.0.4 on 2022-05-19 13:41

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debt_type', models.CharField(choices=[('lend', 'Lend'), ('borrow', 'Borrow')], default='lend', max_length=12)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('returned', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_from_account', to='accounts.account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DebtReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_return_account', to='accounts.account')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.debt')),
            ],
            options={
                'ordering': ['debt__closed', 'debt__name', '-date'],
            },
        ),
    ]
