# Generated by Django 4.0.3 on 2022-03-18 10:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('debts', '0001_initial'), ('debts', '0002_auto_20210601_1009'), ('debts', '0003_auto_20210601_1221'), ('debts', '0004_auto_20210601_1628'), ('debts', '0005_auto_20210604_1303'), ('debts', '0006_auto_20210609_1300'), ('debts', '0007_auto_20210623_1542'), ('debts', '0008_auto_20210827_1414'), ('debts', '0009_auto_20210903_2053'), ('debts', '0010_alter_lentreturn_options_rename_lent_lentreturn_lend_and_more'), ('debts', '0011_remove_borrowreturn_account_and_more'), ('debts', '0012_debt_type'), ('debts', '0013_rename_type_debt_debt_type')]

    initial = True

    dependencies = [
        ('accounts', '0007_account_created'),
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20200123_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('returned', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_from_account', to='accounts.account')),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('journal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journals.journal')),
                ('debt_type', models.CharField(choices=[('lend', 'Lend'), ('borrow', 'Borrow')], default='lend', max_length=12)),
            ],
            options={
                'abstract': False,
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DebtReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_return_account', to='accounts.account')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.debt')),
                ('remark', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
                'ordering': ['debt__closed', 'debt__name', '-date'],
            },
        ),
    ]
