# Generated by Django 3.2.3 on 2021-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='remark',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='borrowreturn',
            name='remark',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lent',
            name='remark',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lentreturn',
            name='remark',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
