# Generated by Django 4.0.3 on 2022-03-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20210805_1008'),
        ('debts', '0001_squashed_0013_rename_type_debt_debt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='debtreturn',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.debt'),
        ),
    ]
