# Generated by Django 4.1.7 on 2023-02-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debts", "0002_alter_debt_price_alter_debt_returned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="debtreturn",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
