# Generated by Django 3.2.3 on 2021-06-01 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debts', '0003_auto_20210601_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrow',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='lent',
            unique_together={('user', 'name')},
        ),
    ]
