# Generated by Django 5.0 on 2023-12-22 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("debts", "0003_alter_debt_price_alter_debtreturn_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debtreturn",
            options={"ordering": ["-debt__date", "debt__name", "-date"]},
        ),
    ]
