# Generated by Django 6.1.1 on 2026-10-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debts", "0004_alter_debtreturn_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="returned",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
