# Generated by Django 3.2.3 on 2021-06-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_auto_20210601_1628'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrow',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lent',
            unique_together=set(),
        ),
    ]
