# Generated by Django 3.2.3 on 2021-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_auto_20210604_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='borrowreturn',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='lent',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='lentreturn',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='borrow',
            name='returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lent',
            name='returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
