# Generated by Django 3.2.3 on 2021-06-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20210617_1042'),
        ('debts', '0006_auto_20210609_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lent',
            name='user',
        ),
        migrations.AddField(
            model_name='borrow',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lent',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journals.journal'),
            preserve_default=False,
        ),
    ]
