# Generated by Django 4.0.1 on 2022-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0011_remove_borrowreturn_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='type',
            field=models.CharField(choices=[('lend', 'Lend'), ('borrow', 'Borrow')], default='lend', max_length=12),
        ),
    ]
