# Generated by Django 4.0.3 on 2022-03-18 10:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('pensions', '0001_initial'), ('pensions', '0002_auto_20191118_2203'), ('pensions', '0003_auto_20200123_1305'), ('pensions', '0004_pension_fee'), ('pensions', '0005_auto_20200224_1434'), ('pensions', '0006_auto_20200323_1338'), ('pensions', '0007_auto_20210623_1542'), ('pensions', '0008_auto_20210805_1008'), ('pensions', '0009_pensiontype_created'), ('pensions', '0010_rename_fees_pensionbalance_fee')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(editable=False, max_length=25)),
                ('journal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pension_types', to='journals.journal')),
                ('created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('journal', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remark', models.TextField(blank=True, max_length=1000)),
                ('pension_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensions.pensiontype')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ['-date', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PensionBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('past_amount', models.FloatField(default=0.0)),
                ('past_fee', models.FloatField(default=0.0)),
                ('fee', models.FloatField(default=0.0)),
                ('invested', models.FloatField(default=0.0)),
                ('incomes', models.FloatField(default=0.0)),
                ('market_value', models.FloatField(default=0.0)),
                ('profit_incomes_proc', models.FloatField(default=0.0)),
                ('profit_incomes_sum', models.FloatField(default=0.0)),
                ('profit_invested_proc', models.FloatField(default=0.0)),
                ('profit_invested_sum', models.FloatField(default=0.0)),
                ('pension_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions_balance', to='pensions.pensiontype')),
            ],
        ),
    ]
