# Generated by Django 4.0.3 on 2022-03-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20210805_1008'),
        ('pensions', '0001_squashed_0010_rename_fees_pensionbalance_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensiontype',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pensiontype',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_types', to='journals.journal'),
        ),
    ]
