# Generated by Django 4.1.3 on 2022-12-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensionbalance',
            name='latest_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
