# Generated by Django 3.0.2 on 2020-02-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0003_auto_20200123_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
