# Generated by Django 4.1.4 on 2022-12-12 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pensions", "0003_pensionbalance_per_year_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pensionbalance",
            name="profit_incomes_proc",
        ),
        migrations.RemoveField(
            model_name="pensionbalance",
            name="profit_incomes_sum",
        ),
    ]
