# Generated by Django 4.1.7 on 2023-02-21 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pensions", "0006_pensionbalance_sold_pensionbalance_sold_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pension",
            name="fee",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="pension",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="fee",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="incomes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="invested",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="market_value",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="past_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="past_fee",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="per_year_fee",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="per_year_incomes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="profit_proc",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="profit_sum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="sold",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pensionbalance",
            name="sold_fee",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
