# Generated by Django 4.0.1 on 2022-02-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0009_pensiontype_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pensionbalance',
            old_name='fees',
            new_name='fee',
        ),
    ]
