# Generated by Django 4.1.7 on 2023-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pensions", "0009_alter_pensionbalance_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pension",
            name="fee",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pension",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
