# Generated by Django 4.2.4 on 2023-08-29 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pensions", "0010_alter_pension_fee_alter_pension_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pensionbalance",
            name="profit_proc",
        ),
    ]
