# Generated by Django 5.0.1 on 2024-02-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pensions", "0012_remove_pensionbalance_invested"),
    ]

    operations = [
        migrations.AddField(
            model_name="pensionbalance",
            name="profit_proc",
            field=models.FloatField(default=0.0),
        ),
    ]
