# Generated by Django 5.2 on 2025-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0013_pensionbalance_profit_proc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pensionbalance',
            options={'ordering': ['year', 'pension_type__pk']},
        ),
        migrations.AddField(
            model_name='pensiontype',
            name='closed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
