# Generated by Django 6.1.1 on 2026-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0003_alter_journal_title"),
        ("pensions", "0016_alter_pensiontype_title"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pensiontype",
            constraint=models.UniqueConstraint(
                fields=("journal", "slug"), name="pensions_pensiontype_unique_slug"
            ),
        ),
    ]
