# Generated by Django 6.1.1 on 2026-10-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pensions", "0017_pensiontype_pensions_pensiontype_unique_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="pensionbalance",
            name="sold_since_check",
            field=models.IntegerField(default=0),
        ),
    ]
