# Generated by Django 2.2.1 on 2019-05-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', 'amount', 'from_account']},
        ),
    ]
