# Generated by Django 2.2.1 on 2019-06-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190523_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', 'price', 'from_account']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='price',
        ),
    ]
