# Generated by Django 4.1.7 on 2023-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0002_alter_savingchange_fee_alter_savingchange_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingchange",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="savingclose",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
