# Generated by Django 6.1.1 on 2026-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0003_alter_savingchange_price_alter_savingclose_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingchange",
            name="fee",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="savingclose",
            name="fee",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
