# Generated by Django 2.2.1 on 2019-06-21 11:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20190610_0855'),
        ('accounts', '0003_auto_20190521_1313'),
        ('transactions', '0003_auto_20190610_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingClose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_from_savings', to='savings.SavingType')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_to_accounts', to='accounts.Account')),
            ],
            options={
                'ordering': ['-date', 'price', 'from_account'],
            },
        ),
        migrations.CreateModel(
            name='SavingChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_from_savings', to='savings.SavingType')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_to_savings', to='savings.SavingType')),
            ],
            options={
                'ordering': ['-date', 'price', 'from_account'],
            },
        ),
    ]
