# Generated by Django 2.2.4 on 2019-09-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20190905_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingchange',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_change_from', to='savings.SavingType'),
        ),
        migrations.AlterField(
            model_name='savingchange',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_change_to', to='savings.SavingType'),
        ),
        migrations.AlterField(
            model_name='savingclose',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_close_from', to='savings.SavingType'),
        ),
        migrations.AlterField(
            model_name='savingclose',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_close_to', to='accounts.Account'),
        ),
    ]
