# Generated by Django 2.2.5 on 2019-09-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20190905_1729'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savingchange',
            index=models.Index(fields=['from_account'], name='transaction_from_ac_366d46_idx'),
        ),
        migrations.AddIndex(
            model_name='savingchange',
            index=models.Index(fields=['to_account'], name='transaction_to_acco_19d2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='savingclose',
            index=models.Index(fields=['from_account'], name='transaction_from_ac_39cba3_idx'),
        ),
        migrations.AddIndex(
            model_name='savingclose',
            index=models.Index(fields=['to_account'], name='transaction_to_acco_eda711_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_account'], name='transaction_from_ac_ad7a61_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_account'], name='transaction_to_acco_70c2d0_idx'),
        ),
    ]
