# Generated by Django 4.0.3 on 2022-03-09 12:04

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Round

def convert_beer_to_av(apps, schema_editor):
    Counter = apps.get_model('counters', 'Counter')
    Counter.objects.filter(counter_type='drinks').update(quantity=Round(F('quantity') * 2.5, 2))


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0002_auto_20200726_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='option',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.RunPython(convert_beer_to_av)
    ]
