# Generated by Django 2.2.7 on 2019-11-13 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DrinkTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
