# Generated by Django 6.0.3 on 2026-03-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='quantity',
            new_name='stdav',
        ),
    ]
