# Generated by Django 4.0.4 on 2022-05-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_delete_drink_drink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'get_latest_by': ['date']},
        ),
    ]
