# Generated by Django 2.2.6 on 2019-10-08 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20191008_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['-date']},
        ),
    ]
