# Generated by Django 3.0.8 on 2020-07-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
        ('drinks', '0002_auto_20191118_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('counters.counter',),
        ),
    ]
