# Generated by Django 2.2.6 on 2019-10-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20191008_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
    ]
