# Generated by Django 4.0.3 on 2022-03-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20200723_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinktarget',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
