# Generated by Django 4.0.3 on 2022-03-14 12:38

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Round

def convert_beer_to_av(apps, schema_editor):
    DrinkTarget = apps.get_model('drinks', 'DrinkTarget')
    DrinkTarget.objects.all().update(quantity=Round((F('quantity') * 2.5)/500, 2), drink_type='beer')

class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_alter_drinktarget_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinktarget',
            name='drink_type',
            field=models.CharField(choices=[('beer', 'Beer'), ('wine', 'Wine'), ('vodka', 'Vodka'), ('stdav', 'Std Av')], default='beer', max_length=7),
        ),
        migrations.RunPython(convert_beer_to_av)
    ]
