# Generated by Django 6.0.7 on 2026-08-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drinks", "0004_drink_converted_from_ml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drink",
            name="option",
            field=models.CharField(
                choices=[
                    ("beer", "Beer"),
                    ("wine", "Wine"),
                    ("vodka", "Vodka"),
                    ("stdav", "Std Av"),
                ],
                default="beer",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="drinktarget",
            name="drink_type",
            field=models.CharField(
                choices=[
                    ("beer", "Beer"),
                    ("wine", "Wine"),
                    ("vodka", "Vodka"),
                    ("stdav", "Std Av"),
                ],
                default="beer",
                max_length=16,
            ),
        ),
    ]
