# Generated by Django 2.2.6 on 2019-11-18 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
            ],
            options={
                'ordering': ['expense_type'],
            },
        ),
        migrations.CreateModel(
            name='IncomePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
            ],
            options={
                'ordering': ['income_type'],
            },
        ),
        migrations.CreateModel(
            name='NecessaryPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
            ],
            options={
                'ordering': ['saving_type'],
            },
        ),
    ]
