# Generated by Django 2.2.7 on 2019-11-13 07:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incomes', '0001_initial'),
        ('expenses', '0001_initial'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NecessaryPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('year', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.SavingType')),
            ],
            options={
                'ordering': ['saving_type'],
                'unique_together': {('year', 'saving_type')},
            },
        ),
        migrations.CreateModel(
            name='IncomePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomes.IncomeType')),
            ],
            options={
                'ordering': ['income_type'],
                'unique_together': {('year', 'income_type')},
            },
        ),
        migrations.CreateModel(
            name='ExpensePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.ExpenseType')),
            ],
            options={
                'ordering': ['expense_type'],
                'unique_together': {('year', 'expense_type')},
            },
        ),
    ]
