# Generated by Django 2.2.6 on 2019-11-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='saving_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.SavingType'),
        ),
    ]
