# Generated by Django 4.0.3 on 2022-03-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20210805_1008'),
        ('plans', '0001_squashed_0005_auto_20210804_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='expenseplan',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_plans', to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='incomeplan',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_plans', to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='necessaryplan',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessary_plans', to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_plans', to='journals.journal'),
        ),
    ]
