# Generated by Django 2.2.1 on 2019-05-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_auto_20190522_1458'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseTypePlan',
            new_name='ExpensePlan',
        ),
    ]
