# Generated by Django 2.2.7 on 2019-11-18 08:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_incometype_user'),
        ('savings', '0002_savingtype_user'),
        ('expenses', '0002_expensetype_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayplan',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='necessaryplan',
            options={'ordering': ['year', 'title']},
        ),
        migrations.AddField(
            model_name='dayplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necessaryplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='necessary_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saving_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('year', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseplan',
            unique_together={('year', 'expense_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='incomeplan',
            unique_together={('year', 'income_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='necessaryplan',
            unique_together={('year', 'title', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='savingplan',
            unique_together={('year', 'saving_type', 'user')},
        ),
    ]
