# Generated by Django 2.2.6 on 2019-11-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incomes', '0001_initial'),
        ('plans', '0002_savingplan_saving_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='necessaryplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessary_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeplan',
            name='income_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomes.IncomeType'),
        ),
        migrations.AddField(
            model_name='incomeplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseplan',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.ExpenseType'),
        ),
        migrations.AddField(
            model_name='expenseplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savingplan',
            unique_together={('year', 'saving_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='necessaryplan',
            unique_together={('year', 'title', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='incomeplan',
            unique_together={('year', 'income_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseplan',
            unique_together={('year', 'expense_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('year', 'user')},
        ),
    ]
