# Generated by Django 2.2.6 on 2019-10-07 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190528_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='year',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='expenseplan',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='incomeplan',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.CreateModel(
            name='NecessaryPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('february', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('march', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('april', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('june', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('july', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('august', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('september', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('october', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('november', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('december', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('year', 'title')},
            },
        ),
    ]
