# Generated by Django 3.2.3 on 2021-06-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0005_auto_20210616_1325'),
        ('savings', '0004_auto_20210616_1325'),
        ('journals', '0002_auto_20210617_1042'),
        ('expenses', '0007_auto_20210617_1042'),
        ('plans', '0003_auto_20191118_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseplan',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_plans', to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeplan',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income_plans', to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necessaryplan',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='necessary_plans', to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingplan',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saving_plans', to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('year', 'journal')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseplan',
            unique_together={('year', 'expense_type', 'journal')},
        ),
        migrations.AlterUniqueTogether(
            name='incomeplan',
            unique_together={('year', 'income_type', 'journal')},
        ),
        migrations.AlterUniqueTogether(
            name='necessaryplan',
            unique_together={('year', 'title', 'journal')},
        ),
        migrations.AlterUniqueTogether(
            name='savingplan',
            unique_together={('year', 'saving_type', 'journal')},
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expenseplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='incomeplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='necessaryplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savingplan',
            name='user',
        ),
    ]
