# Generated by Django 5.0 on 2023-12-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_alter_expense_price"),
        ("journals", "0001_initial"),
        ("plans", "0003_alter_dayplan_april_alter_dayplan_august_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="necessaryplan",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="necessaryplan",
            name="expense_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.expensetype",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="necessaryplan",
            unique_together={("year", "title", "expense_type", "journal")},
        ),
    ]
