# Generated by Django 5.0.1 on 2024-01-25 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0004_alter_necessaryplan_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="necessaryplan",
            options={"ordering": ["year", "expense_type", "title"]},
        ),
    ]
