# Generated by Django 6.0.3 on 2026-04-08 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_alter_expense_price"),
        ("journals", "0001_initial"),
        ("plans", "0006_alter_necessaryplan_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="necessaryplan",
            unique_together={("year", "month", "title", "expense_type", "journal")},
        ),
    ]
