# Generated by Django 6.0.3 on 2026-04-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_necessaryplan_unique_together'),
        ('plans', '0008_convert_wide_tables_into_tall'),
    ]

    operations = [
    ]
