# Generated by Django 6.1.1 on 2026-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0012_alter_necessaryplan_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayplan",
            name="month",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="dayplan",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="expenseplan",
            name="month",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="expenseplan",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="incomeplan",
            name="month",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="incomeplan",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="necessaryplan",
            name="month",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="necessaryplan",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="savingplan",
            name="month",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="savingplan",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
