# Generated by Django 4.0.3 on 2022-03-18 10:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('incomes', '0001_initial'), ('incomes', '0002_auto_20191118_2203'), ('incomes', '0003_auto_20200123_1305'), ('incomes', '0004_auto_20200323_1338'), ('incomes', '0005_auto_20210623_1542'), ('incomes', '0006_incometype_type'), ('incomes', '0007_auto_20210805_1008')]

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(editable=False, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remark', models.TextField(blank=True, max_length=1000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='accounts.account')),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomes.incometype')),
            ],
            options={
                'ordering': ['-date', 'price'],
            },
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['account', 'income_type'], name='incomes_inc_account_90c123_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['income_type'], name='incomes_inc_income__b6fb65_idx'),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='title',
            field=models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='incometype',
            unique_together={('user', 'title')},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
        migrations.AddField(
            model_name='incometype',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income_types', to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='incometype',
            unique_together={('journal', 'title')},
        ),
        migrations.RemoveField(
            model_name='incometype',
            name='user',
        ),
        migrations.AddField(
            model_name='incometype',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('dividents', 'Dividents'), ('other', 'Other')], default='salary', max_length=12),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='slug',
            field=models.SlugField(editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='title',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
