# Generated by Django 2.2 on 2019-05-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=254)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='income',
            name='income_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incomes.IncomeName'),
            preserve_default=False,
        ),
    ]
