# Generated by Django 3.0.2 on 2020-01-23 11:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incomes', '0002_auto_20191118_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='title',
            field=models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='incometype',
            unique_together={('user', 'title')},
        ),
    ]
