# Generated by Django 2.2 on 2019-05-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_auto_20190525_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income_name',
            new_name='income_type',
        ),
    ]
