# Generated by Django 2.2 on 2019-05-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0003_auto_20190525_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeName',
            new_name='IncomeType',
        ),
    ]
