# Generated by Django 3.0.4 on 2020-03-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0003_auto_20200123_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
    ]
