# Generated by Django 3.2.3 on 2021-06-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('incomes', '0004_auto_20200323_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometype',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income_types', to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='incometype',
            unique_together={('journal', 'title')},
        ),
        migrations.RemoveField(
            model_name='incometype',
            name='user',
        ),
    ]
