# Generated by Django 2.2.1 on 2019-06-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0004_auto_20190525_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', 'price']},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='amount',
            new_name='price',
        ),
    ]
