# Generated by Django 2.2.4 on 2019-09-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0005_auto_20190610_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='accounts.Account'),
        ),
    ]
