# Generated by Django 6.1.1 on 2026-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incomes", "0005_alter_incometype_title"),
        ("journals", "0003_alter_journal_title"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="incometype",
            constraint=models.UniqueConstraint(
                fields=("journal", "slug"), name="incomes_incometype_unique_slug"
            ),
        ),
    ]
