# Generated by Django 3.2.5 on 2021-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0005_auto_20210623_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometype',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('dividents', 'Dividents'), ('other', 'Other')], default='salary', max_length=12),
        ),
    ]
