# Generated by Django 2.2.5 on 2019-09-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0006_auto_20190905_0959'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['account', 'income_type'], name='incomes_inc_account_90c123_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['income_type'], name='incomes_inc_income__b6fb65_idx'),
        ),
    ]
