# Generated by Django 2.2.1 on 2019-05-27 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('author', models.CharField(max_length=254, validators=[django.core.validators.MinValueValidator(3)])),
                ('title', models.CharField(max_length=254, validators=[django.core.validators.MinValueValidator(3)])),
            ],
            options={
                'ordering': ['-started', 'author'],
            },
        ),
    ]
