# Generated by Django 4.0.3 on 2022-03-18 09:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bookkeeping', '0001_initial'), ('bookkeeping', '0002_auto_20191118_2203'), ('bookkeeping', '0003_alter_savingworth_options'), ('bookkeeping', '0004_alter_accountworth_options_and_more'), ('bookkeeping', '0005_alter_savingworth_date'), ('bookkeeping', '0006_alter_accountworth_date_alter_pensionworth_date')]

    initial = True

    dependencies = [
        ('accounts', '0002_account_user'),
        ('pensions', '0001_initial'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingWorth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_worth', to='savings.savingtype')),
            ],
            options={
                'get_latest_by': ['date'],
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AccountWorth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_worth', to='accounts.account')),
            ],
            options={
                'get_latest_by': ['date'],
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PensionWorth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('pension_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions_worth', to='pensions.pensiontype')),
            ],
            options={
                'get_latest_by': ['date'],
                'ordering': ['-date'],
            },
        ),
    ]
