# Generated by Django 2.2.3 on 2019-08-01 11:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0002_auto_20190610_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingWorth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.SavingType')),
            ],
        ),
    ]
