# Generated by Django 2.2.3 on 2019-08-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingworth',
            old_name='created',
            new_name='date',
        ),
    ]
