# Generated by Django 3.2 on 2021-05-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_auto_20191118_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingworth',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
    ]
