# Generated by Django 4.0 on 2022-01-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_alter_savingworth_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountworth',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='pensionworth',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
    ]
