# Generated by Django 2.2.4 on 2019-08-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_accountworth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountworth',
            options={'get_latest_by': ['date']},
        ),
        migrations.AlterModelOptions(
            name='savingworth',
            options={'get_latest_by': ['date']},
        ),
    ]
