# Generated by Django 3.2.3 on 2021-06-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeping', '0004_bookkeeping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping', to=settings.AUTH_USER_MODEL),
        ),
    ]
