# Generated by Django 4.0.1 on 2022-02-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0004_alter_accountworth_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingworth',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
