# Generated by Django 2.2.4 on 2019-09-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0004_auto_20190830_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountworth',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_worth', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='savingworth',
            name='saving_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_worth', to='savings.SavingType'),
        ),
    ]
