# Generated by Django 4.2 on 2023-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookkeeping",
            "0004_alter_accountworth_price_alter_pensionworth_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountworth",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pensionworth",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savingworth",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
