# Generated by Django 6.1.1 on 2026-10-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookkeeping",
            "0005_alter_accountworth_price_alter_pensionworth_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountworth",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="pensionworth",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="savingworth",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
