# Generated by Django 2.2.6 on 2019-10-31 13:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensions', '0001_initial'),
        ('bookkeeping', '0005_auto_20190906_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionWorth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pension_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions_worth', to='pensions.PensionType')),
            ],
            options={
                'get_latest_by': ['date'],
            },
        ),
    ]
