# Generated by Django 3.2.3 on 2021-06-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_alter_bookkeeping_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookkeeping',
        ),
    ]
