# Generated by Django 4.0.1 on 2022-02-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_alter_savingworth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountworth',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pensionworth',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
