# Generated by Django 3.2.3 on 2021-06-23 12:42

from django.db import migrations, models
import django.db.models.deletion
import project.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('users', '0002_auto_20201001_1445'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', project.users.managers.KeepingUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='journals.journal'),
            preserve_default=False,
        ),
    ]
