# Generated by Django 6.0.7 on 2026-08-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="drink_type",
            field=models.CharField(
                choices=[
                    ("beer", "Beer"),
                    ("wine", "Wine"),
                    ("vodka", "Vodka"),
                    ("stdav", "Std Av"),
                ],
                default="beer",
                max_length=16,
            ),
        ),
    ]
