# Generated by Django 4.0.3 on 2022-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drink_type',
            field=models.CharField(default='beer', max_length=16),
        ),
    ]
