# Generated by Django 3.2.3 on 2021-06-23 12:42


import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from ..models import Journal



def journal(apps, schema_editor):

    Journal.objects.create(
        title='Buh',
        slug='buh'
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(editable=False, max_length=254)),
                ('first_record', models.DateField(default=datetime.date.today, editable=False)),
                ('unnecessary_expenses', models.CharField(blank=True, max_length=254, null=True)),
                ('unnecessary_savings', models.BooleanField(default=False))
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(journal),
    ]
