# Generated by Django 3.2.3 on 2021-06-16 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from ..models import Journal
from ...users.models import User

def journal(apps, schema_editor):
    user = User.objects.get(pk=1)

    Journal.objects.create(
        user=user,
        year=2021,
        month=6,
        first_record=datetime.date(2004, 1, 1)
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('first_record', models.DateField(default=datetime.date.today, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(journal),
    ]
