# Generated by Django 3.2.5 on 2021-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
