# Generated by Django 3.2.3 on 2021-07-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='not_use_expenses',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='not_use_savings',
            field=models.BooleanField(default=False),
        ),
    ]
