# Generated by Django 3.2.3 on 2021-07-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20210714_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='not_use_expenses',
            new_name='unnecessary_expenses',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='not_use_savings',
            new_name='unnecessary_savings',
        ),
    ]
