# Generated by Django 6.1.1 on 2026-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0003_alter_journal_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="lang",
            field=models.CharField(
                choices=[("en", "English"), ("lt", "Lithuanian")],
                default="en",
                max_length=2,
            ),
        ),
    ]
