# Generated by Django 2.1.7 on 2019-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True, verbose_name='Pavadinimas')),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
