# Generated by Django 4.0.3 on 2022-03-18 09:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_account_user'), ('accounts', '0003_account_closed'), ('accounts', '0004_auto_20200123_1305'), ('accounts', '0005_auto_20210623_1542'), ('accounts', '0006_auto_20210805_1008'), ('accounts', '0007_account_created')]

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(editable=False, max_length=25)),
                ('order', models.PositiveIntegerField(default=10)),
                ('closed', models.PositiveIntegerField(blank=True, null=True)),
                ('journal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='journals.journal')),
                ('created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('journal', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('past', models.FloatField(default=0.0)),
                ('incomes', models.FloatField(default=0.0)),
                ('expenses', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('have', models.FloatField(default=0.0)),
                ('delta', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_balance', to='accounts.account')),
            ],
        ),
    ]
