# Generated by Django 2.2.7 on 2019-11-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
