# Generated by Django 4.1.7 on 2023-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_accountbalance_latest_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbalance",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="delta",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="expenses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="have",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="incomes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="past",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
