# Generated by Django 2.2.1 on 2019-07-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190521_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='account',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
