# Generated by Django 4.1.7 on 2023-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_accountbalance_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbalance",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="delta",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="expenses",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="have",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="incomes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="past",
            field=models.IntegerField(default=0),
        ),
    ]
