# Generated by Django 3.2.3 on 2021-06-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('accounts', '0004_auto_20200123_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='journals.journal'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('journal', 'title')},
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
