# Generated by Django 2.2.1 on 2019-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190729_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
