# Generated by Django 6.0.3 on 2026-04-12 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accountbalance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Title can only contain letters, numbers, spaces, hyphens, and underscores.', regex='^[ \\w\\-\\.]+$')]),
        ),
    ]
