# Generated by Django 6.1.1 on 2026-10-01 08:08

import django.core.validators
from django.db import migrations, models

import project.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_account_slug_alter_account_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        message="Title can only contain letters, numbers, spaces, hyphens, and underscores.",
                        regex="^[ \\w\\-\\.]+$",
                    ),
                    project.core.validators.validate_title_slug,
                ],
            ),
        ),
    ]
