# Generated by Django 2.2.6 on 2019-10-22 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191012_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('past', models.FloatField(default=0.0)),
                ('incomes', models.FloatField(default=0.0)),
                ('expenses', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('have', models.FloatField(default=0.0)),
                ('delta', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_balance', to='accounts.Account')),
            ],
        ),
    ]
