# Generated by Django 6.1.1 on 2026-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_account_title"),
        ("journals", "0003_alter_journal_title"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("journal", "slug"), name="accounts_account_unique_slug"
            ),
        ),
    ]
