# Generated by Django 2.2.6 on 2019-11-13 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
