# Generated by Django 4.1.7 on 2023-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_expense_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
