# Generated by Django 2.2.1 on 2019-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20190515_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='remark',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
