# Generated by Django 6.1.1 on 2026-09-24 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_alter_expensename_slug_alter_expensetype_slug_and_more"),
        ("journals", "0002_alter_journal_slug_alter_journal_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "expense_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_keywords",
                        to="expenses.expensename",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_keywords",
                        to="journals.journal",
                    ),
                ),
            ],
            options={
                "unique_together": {("journal", "keyword")},
            },
        ),
    ]
