# Generated by Django 3.1.2 on 2021-01-28 16:34

import django.core.validators
from django.db import migrations, models
import project.expenses.helpers.models_helper


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20200323_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, upload_to=project.expenses.helpers.models_helper.upload_attachment, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'xls', 'xlsx', 'doc', 'docx'])]),
        ),
    ]
