# Generated by Django 2.2.1 on 2019-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20190516_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exception',
            field=models.BooleanField(default=False),
        ),
    ]
