# Generated by Django 6.1.1 on 2026-10-01 08:08

import django.core.validators
from django.db import migrations, models

import project.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0006_expensekeyword_keyword_accent_sensitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensename",
            name="title",
            field=models.CharField(
                max_length=254,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    project.core.validators.validate_title_slug,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expensetype",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        message="Title can only contain letters, numbers, spaces, hyphens, and underscores.",
                        regex="^[ \\w\\-\\.]+$",
                    ),
                    project.core.validators.validate_title_slug,
                ],
            ),
        ),
    ]
