# Generated by Django 6.1.1 on 2026-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_alter_expensename_title_alter_expensetype_title"),
        ("journals", "0003_alter_journal_title"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="expensename",
            constraint=models.UniqueConstraint(
                fields=("parent", "slug"), name="expenses_expensename_unique_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensetype",
            constraint=models.UniqueConstraint(
                fields=("journal", "slug"), name="expenses_expensetype_unique_slug"
            ),
        ),
    ]
