# Generated by Django 2.2 on 2019-05-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_exception'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensesubname',
            unique_together={('title', 'parent')},
        ),
    ]
