# Generated by Django 3.2.7 on 2021-09-10 13:13

from django.db import migrations, models
import project.expenses.helpers.models_helper


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20210805_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.ImageField(blank=True, upload_to=project.expenses.helpers.models_helper.upload_attachment),
        ),
    ]
