# Generated by Django 6.1.1 on 2026-10-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0008_expensename_expenses_expensename_unique_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensename",
            name="slug",
            field=models.SlugField(editable=False, max_length=254),
        ),
    ]
