# Generated by Django 2.2 on 2019-05-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20190516_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseName',
            new_name='ExpenseType',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'category', 'sub_category', 'price']},
        ),
        migrations.AlterModelOptions(
            name='expensesubname',
            options={'ordering': ['parent', 'title']},
        ),
    ]
