# Generated by Django 2.2 on 2019-05-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_auto_20190516_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseSubName',
            new_name='ExpenseName',
        ),
    ]
