# Generated by Django 2.2.1 on 2019-05-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20190516_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'category', 'expense_name', 'price']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='sub_category',
            new_name='expense_name',
        ),
    ]
