# Generated by Django 2.2.1 on 2019-05-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_auto_20190517_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'expense_type', 'expense_name', 'price']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='expense_type',
        ),
    ]
