# Generated by Django 2.2.1 on 2019-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_auto_20190521_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensename',
            name='valid_for',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
