# Generated by Django 2.2.1 on 2019-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_auto_20190522_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='necessary',
            field=models.BooleanField(default=False),
        ),
    ]
