# Generated by Django 2.2.5 on 2019-09-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_auto_20190905_0959'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['account', 'expense_type'], name='expenses_ex_account_5de667_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type'], name='expenses_ex_expense_3c4432_idx'),
        ),
    ]
