# Generated by Django 2.2.6 on 2019-10-12 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_auto_20190926_1602'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='expensename',
        #     name='title',
        #     field=models.CharField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        # ),
        migrations.AlterField(
            model_name='expensetype',
            name='title',
            field=models.CharField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
