# Generated by Django 2.2.6 on 2019-10-14 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_auto_20191012_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensename',
            name='title',
            field=models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
