# Generated by Django 2.2.6 on 2019-10-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_auto_20191014_0848'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx'),
        ),
    ]
