# Generated by Django 2.2.6 on 2019-10-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_auto_20191030_1402'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_name'], name='expenses_ex_expense_bfb2f7_idx'),
        ),
    ]
