# Generated by Django 3.0.8 on 2020-07-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counters', '0002_auto_20200726_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('counters.counter',),
        ),
    ]
