# Generated by Django 4.0.4 on 2022-05-19 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Count",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "get_latest_by": ["date"],
            },
        ),
        migrations.CreateModel(
            name="CountType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=25,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=25)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
