# Generated by Django 4.0.4 on 2022-05-19 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counttype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='count',
            name='count_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='counts.counttype'),
        ),
        migrations.AddField(
            model_name='count',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='counttype',
            unique_together={('user', 'title')},
        ),
    ]
