# Generated by Django 4.0.4 on 2022-04-28 08:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def copy_data_from_counters(apps, schema_editor):
    Counter = apps.get_model('counters', 'Counter')
    Count = apps.get_model('counts', 'Count')
    CountType = apps.get_model('counts', 'CountType')

    count_types = CountType.objects.all()
    counter = Counter.objects.exclude(counter_type='drinks')

    for i in counter:
        count_type = count_types.get(title=i.counter_type)
        Count.objects.create(user=i.user, count_type=count_type, quantity=i.quantity, date=i.date)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counts', '0002_counttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('count_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='counts.counttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.RunPython(copy_data_from_counters)
    ]
