# Generated by Django 6.1.1 on 2026-10-01 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counts", "0004_alter_counttype_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="counttype",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="counts_counttype_unique_slug"
            ),
        ),
    ]
