# Generated by Django 2.2.1 on 2019-06-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saving',
            old_name='amount',
            new_name='price',
        ),
    ]
