# Generated by Django 2.2.6 on 2019-11-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingtype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingbalance',
            name='saving_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_balance', to='savings.SavingType'),
        ),
        migrations.AddField(
            model_name='saving',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='saving',
            name='saving_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.SavingType'),
        ),
        migrations.AddIndex(
            model_name='saving',
            index=models.Index(fields=['account', 'saving_type'], name='savings_sav_account_119c89_idx'),
        ),
        migrations.AddIndex(
            model_name='saving',
            index=models.Index(fields=['saving_type'], name='savings_sav_saving__07f3d9_idx'),
        ),
    ]
