# Generated by Django 2.2.7 on 2019-11-15 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingtype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saving_types', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
