# Generated by Django 2.2.4 on 2019-09-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20190610_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='accounts.Account'),
        ),
    ]
