# Generated by Django 2.2.5 on 2019-09-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20190906_0938'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='saving',
            index=models.Index(fields=['account', 'saving_type'], name='savings_sav_account_119c89_idx'),
        ),
        migrations.AddIndex(
            model_name='saving',
            index=models.Index(fields=['saving_type'], name='savings_sav_saving__07f3d9_idx'),
        ),
    ]
