# Generated by Django 2.2.6 on 2019-10-12 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_auto_20190926_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingtype',
            name='title',
            field=models.CharField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
