# Generated by Django 3.2.5 on 2021-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_auto_20210623_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingtype',
            name='type',
            field=models.CharField(choices=[('shares', 'Shares'), ('funds', 'Funds'), ('pensions', 'Pensions')], default='funds', max_length=12),
        ),
    ]
