# Generated by Django 3.2.5 on 2021-08-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_savingtype_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingtype',
            options={'ordering': ['type', 'title']},
        ),
    ]
