# Generated by Django 2.2.6 on 2019-10-26 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_savingtype_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1974), django.core.validators.MaxValueValidator(2050)])),
                ('past_amount', models.FloatField(default=0.0)),
                ('past_fee', models.FloatField(default=0.0)),
                ('fees', models.FloatField(default=0.0)),
                ('invested', models.FloatField(default=0.0)),
                ('incomes', models.FloatField(default=0.0)),
                ('market_value', models.FloatField(default=0.0)),
                ('profit_incomes_proc', models.FloatField(default=0.0)),
                ('profit_incomes_sum', models.FloatField(default=0.0)),
                ('profit_invested_proc', models.FloatField(default=0.0)),
                ('profit_invested_sum', models.FloatField(default=0.0)),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_balance', to='savings.SavingType')),
            ],
        ),
    ]
