# Generated by Django 4.1.7 on 2023-02-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0007_alter_saving_fee_alter_saving_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingbalance",
            name="profit_proc",
            field=models.FloatField(default=0.0),
        ),
    ]
