# Generated by Django 4.1.7 on 2023-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "savings",
            "0009_alter_savingbalance_fee_alter_savingbalance_incomes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="saving",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
