# Generated by Django 4.2.4 on 2023-08-29 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0010_alter_saving_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingbalance",
            name="profit_proc",
        ),
    ]
