# Generated by Django 5.0.1 on 2024-02-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0012_remove_savingbalance_invested"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingbalance",
            name="profit_proc",
            field=models.FloatField(default=0.0),
        ),
    ]
