# Generated by Django 5.1.4 on 2025-01-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0013_savingbalance_profit_proc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saving",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
