# Generated by Django 5.1.4 on 2025-01-03 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0014_alter_saving_price"),
        ("savings", "0014_alter_savingtype_slug_alter_savingtype_title"),
    ]

    operations = []
