# Generated by Django 5.2 on 2025-05-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0015_merge_20250103_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingbalance',
            options={'ordering': ['year', 'saving_type__pk']},
        ),
    ]
