# Generated by Django 6.1.1 on 2026-10-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0017_savingtype_savings_savingtype_unique_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingtype",
            name="fee_source",
            field=models.CharField(
                choices=[
                    ("investment", "from the investment"),
                    ("account", "from the account"),
                ],
                default="investment",
                max_length=12,
            ),
        ),
    ]
