# Generated by Django 6.1.1 on 2026-10-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0018_savingtype_fee_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingbalance",
            name="sold_since_check",
            field=models.IntegerField(default=0),
        ),
    ]
